export const FETCH_PLAYLISTS_FROM_API = 'FETCH_PLAYLISTS_FROM_API'
export const FETCH_TRACKS_FROM_SELECTED_PLAYLIST =
	'FETCH_TRACKS_FROM_SELECTED_PLAYLIST'
export const NEXT_TRACK = 'NEXT_TRACK'
export const PREV_TRACK = 'PREV_TRACK'
export const PLAY_TRACK = 'PLAY_TRACK'
export const PAUSE_TRACK = 'PAUSE_TRACK'
